version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-product-image-generator
        volumes:
            - .:/var/www
